### ISSUE TITLE
Serial Connection to MH871-MK2

### ISSUE THREAD

**Issue by danzeeeman** [makerslocal/localplot#1]
What are the:
- Baud Rate
- Parity
- Bytesize
## \- Stopbits
- XON/XOFF
- RTS/CTS
- DSR/DTR 

settings you are using?

**Comment by ctag** [comment]
Hi,

First, the program's getting some heavy changes while I try to sort things for inkscape+hpgl. Master branch is unstable. I've tagged a version 0.1 of the commit which compiles and can read/write hpgl to a serial port.

The defaults for the program:
- Baud: 9600
- Parity: none
- Bytesize: 8
- Stopbits: 1
- No radio buttons checked

Are what work for our vinyl cutter.

I'll close the issue here. If these settings don't work, or you have additional questions, feel free to reopen it.
